services:
  postgres:
    image: postgres:latest
    container_name: owner-one-postgres
    env_file: [.env]
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    container_name: owner-one-redis
    platform: ${PLATFORM}
    image: docker.io/redis/redis-stack
    # command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
      - "8001:8001"
    networks:
      - redis-network
    env_file: [ .env ]
    volumes:
      - "./volumes/redis:/data"
    restart: unless-stopped

volumes:
  redis-data:
    driver: local
networks:
  redis-network:
    driver: bridge
  postgres-network:
    driver: bridge

